### ISSUE TITLE
Unit Commandblocks Crash

### ISSUE THREAD

**Issue by Glacier7975** [sk7725/Commandblocks#3]
When I try to remove Unit Commandblocks they just crash the game (on Android idk if other platforms also crash)

**Comment by ActualWina** [comment]
Same here

**Comment by ghost** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/58987087/80020794-f901a800-84af-11ea-9ce5-48032414fbec.png)

**Comment by Glacier7975** [comment]
In case you need the crash log here it is:

> EcmaError: 'ReferenceError: "commandblocksr" is not defined. (commandblockunit#15)'
ScriptRuntime.constructError: 4256
ScriptRuntime.constructError: 4234
ScriptRuntime.notFoundError: 4324
ScriptRuntime.name: 1935
commandblockunit_12._c_anonymous_2: 15
commandblockunit_12.call: 47
ContextFactory.doTopCall: 409
ScriptRuntime.doTopCall: 3566
commandblockunit_12.call: 18
JavaAdapter.doCall: 613
JavaAdapter.callMethod: 594
adapter7.removed: 29
Tile.preChanged: 443
Tile.setBlock: 158
Tile.set: 199
Build.beginBreak: 39
Call.beginBreak: 31
BuilderTrait$-CC.$default$updateBuilding: 73
Player.updateBuilding: 0
Player.updateMechanics: 461
Player.update: 565
EntityGroup.update: 51
Logic.update: 248
ApplicationCore.update: 36
ClientLauncher.update: 138
AndroidGraphics.lambda$onDrawFrame$1: 436
-$$Lambda$AndroidGraphics$-UMZ7f6RjD4gjnI5A71J9uqnjKo.run: 2
AndroidGraphics.runProtected: 479
AndroidGraphics.onDrawFrame: 433
GLSurfaceView$GLThread.guardedRun: 1573
GLSurfaceView$GLThread.run: 1272

**Comment by sk7725** [comment]
Sorry, remove() had a typo. Fixed!
