### ISSUE TITLE
Commandb crash

### ISSUE THREAD

**Issue by ThePythonGuy3** [sk7725/Commandblocks#35]
Sometimes when you add a command to a commandb, game says "Cant read `message` from undefined" and crashes.

**Comment by sk7725** [comment]
Please post the full crash log

**Comment by ThePythonGuy3** [comment]
[last_log.txt](https://github.com/sk7725/Commandblocks/files/4840730/last_log.txt)

**Comment by ThePythonGuy3** [comment]
[crash-report-06_27_2020_16_59_39.txt](https://github.com/sk7725/Commandblocks/files/4840735/crash-report-06_27_2020_16_59_39.txt)

**Comment by sk7725** [comment]
Fixed via spammimg try-catches, will fix that later

**Comment by sk7725** [comment]
later is never
