### ISSUE TITLE
README.md is outdated

### ISSUE THREAD

**Issue by BlueMoonJune** [sk7725/Commandblocks#37]
I would like to know how to use the new blocks but the readme is not updated yet. It would be nice if you fixed that.

**Comment by sk7725** [comment]
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i wish it magically did that on its own

**Comment by ThePythonGuy3** [comment]
Mayyybe... Tomorrow I'll update it. I am a magician, so yes, it will magically update by itself.

**Comment by sk7725** [comment]
:heart:

**Comment by ghost** [comment]
oh no

**Comment by ThePythonGuy3** [comment]
on ho

**Comment by ThePythonGuy3** [comment]
Np

**Comment by ThePythonGuy3** [comment]
No longer outdated... Some magic happened here

**Comment by sk7725** [comment]
how is $ notation going?

**Comment by Gwapowo** [comment]
Banana

**Comment by ThePythonGuy3** [comment]
ehhh.. no
