### ISSUE TITLE
2x2 blocks are transparent

### ISSUE THREAD

**Issue by Glacier7975** [sk7725/Commandblocks#4]
When a command block places a 2x2 block it gets transparent but after rejoining they get normal

![20200511_111343](https://user-images.githubusercontent.com/59489532/81545109-b3325400-9378-11ea-998a-7443a31a62da.jpg)

**Comment by sk7725** [comment]
This is semi-intended, but this feature will be pushed to 'force', making this no longer an issue soon.

**Comment by sk7725** [comment]
This is actually what i want it to be like, you may use `/setblock <x> <y> <block> <rotation> <team> build` to place a block as if it were a player.
