### ISSUE TITLE
Campfire in the Research Tree yet Unresearchable

### ISSUE THREAD

**Issue by ridesdragons** [sk7725/Commandblocks#43]
In order to research the campfire, you'd need to ship out 640 copper, 830 lead, and 830 coal. however... coal is not shippable or storable. as such, there's no way to research that tech (unless you use some cursed mod that makes coal shippable, like whatever mod allows you to ship scrap. absolutely cursed)

**Comment by ThePythonGuy3** [comment]
do you know what loaders are?

**Comment by ThePythonGuy3** [comment]
> (unless you use some cursed mod that makes coal shippable, like whatever mod allows you to ship scrap. absolutely cursed)

commandblocks is that mod

**Comment by ghost** [comment]
Use loader, build the loader next to your core, and input coal inside the block.

**Comment by ThePythonGuy3** [comment]
too late, gdeft

**Comment by ghost** [comment]
Nothing is ever too late.

**Comment by ThePythonGuy3** [comment]
say that when you die

**Comment by ghost** [comment]
that when you die

**Comment by ThePythonGuy3** [comment]
# h

**Comment by sk7725** [comment]
Launched coal(via loader) will not be shown in the tree but still be there. If you collect the needed amounts you will be able to research it.

**Comment by ridesdragons** [comment]
sorry, didn't know about loaders. started a fresh campaign with a bunch of mods, haven't unlocked those yet
