### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by MIGHTYCLIMBER** [sk7725/Commandblocks#5]
If u can improve the summon command so I can tested modded unit

**Comment by MIGHTYCLIMBER** [comment]
It will be better if the summon command can summon a modded units

**Comment by sk7725** [comment]
A complete overhaul allowing modded stuff is planned.

**Comment by MIGHTYCLIMBER** [comment]
I mean would it be nice if the command block can read any modded units and summon it

**Comment by sk7725** [comment]
It can read modded units, use `[name=mod-name-unit-name]`(same as bundles).

**Comment by MIGHTYCLIMBER** [comment]
It can't summon the unit

**Comment by sk7725** [comment]
`/summon` and `/effect` now can use modded stuff via `mod-name-unit/effect-name`, `/fire` and `fx` can use id for modded stuff.
