### ISSUE TITLE
When adding the mod I get an error

### ISSUE THREAD

**Issue by Hubir7** [sk7725/Commandblocks#56]
[last_log.txt](https://github.com/sk7725/Commandblocks/files/5025124/last_log.txt)

**Comment by sk7725** [comment]
Did you try to load this mod in 6.0?

**Comment by Hubir7** [comment]
No, I'm on version 104.10, maybe the problem is that when the mod asked me to restart mindustry the laptop ran out of battery

**Comment by sk7725** [comment]
Well I guess that was the problem.
