### ISSUE TITLE
Pulse Block / Repeater Block

### ISSUE THREAD

**Issue by RebornTrack970** [sk7725/Commandblocks#57]
Please add an pulse extender like the redstone repeater in Minecraft.
I tried making a triple piston extender and it worked but it was a lot harder because there is no delay block.

**Comment by sk7725** [comment]
Use ~~the superior item logic~~Detecting Routers. Also try Scidustrymod, it has all that you need. @eldoofus

**Comment by RebornTrack970** [comment]
Thank you, I used the detecting router technic to make a triple pistone already, but I was thinking repeaters would make that easier,
