### ISSUE TITLE
Commandblocks campaign map

### ISSUE THREAD

**Issue by FreezeMandu** [sk7725/Commandblocks#61]
[Fortress_re.zip](https://github.com/sk7725/Commandblocks/files/5334831/Fortress_re.zip)

I modified the basic map, Fortress.

**Comment by CaeciliusInHorto** [comment]
I used the Github tag access feature on Mindustry on Mac, and it told me that Mindustry needed to restart. I pressed the restart button, and when I tried reopening Mindustry it failed and the application quit. I tried reopening again, same thing happened.

**Comment by GglLfr** [comment]
> I used the Github tag access feature on Mindustry on Mac, and it told me that Mindustry needed to restart. I pressed the restart button, and when I tried reopening Mindustry it failed and the application quit. I tried reopening again, same thing happened.

Nothing works on Mac

**Comment by Goobrr** [comment]
As a mac user i can confirm

**Comment by CaeciliusInHorto** [comment]
> > I used the Github tag access feature on Mindustry on Mac, and it told me that Mindustry needed to restart. I pressed the restart button, and when I tried reopening Mindustry it failed and the application quit. I tried reopening again, same thing happened.
> 
> Nothing works on Mac

Mechanical-Warfare worked just fine

**Comment by GglLfr** [comment]
> > Nothing works on Mac
> 
> Mechanical-Warfare worked just fine

That's incorrect. I can guarantee that you haven't updated MW 'till the last version.
