### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by IFOZVORTEX** [sk7725/Commandblocks#65]
When i added the mod to my game with github tag access feature (pc version Windows 32bits) everything was fine, but when I activated the mod, closed the game and launch it back, it crashes in the loading screen and I looked up on my computer CPU, and it wasn't even half of its capabilities so it's not a regular crash because the game is too heavy or something like that.

So I don't understand why it crashes.

Can you help me please?

Here is the crash report.

[crash-report-11_27_2020_19_00_53.txt](https://github.com/sk7725/Commandblocks/files/5609168/crash-report-11_27_2020_19_00_53.txt)

**Comment by sk7725** [comment]
That looks like a 6.0 crash log(before the log rehaul), as far as I can tell. This is a 5.0 mod.
