### ISSUE TITLE
not work on v6

### ISSUE THREAD

**Issue by gh-doot** [sk7725/Commandblocks#66]
v6 is here, v5 is discarded/gone, so the mod would not work and do nothing

**Comment by sk7725** [comment]
5.0 is still here - in our hearts.

For a 6.0 mod good enough to rival with CB, I suggest you this: https://youtu.be/BjDd5EQHpu8

Stay tuned!

**Comment by Txar** [comment]
oh no

**Comment by gh-doot** [comment]
> 
> 
> 5.0 is still here - in our hearts.
> 
> For a 6.0 mod good enough to rival with CB, I suggest you this: https://youtu.be/BjDd5EQHpu8
> 
> Stay tuned!

'5.0 is still here- in our hearts.'
agree, like, if one downloaded it already, you have v5
v5 might be missed af 
'rival with cb'
for sure
'stay tuned'
yeah im liking this mod even tho i dont have v5
i can see via the assets 👍 
im waiting for project unity release too

**Comment by gh-doot** [comment]
> 
> 
> oh no

?
